version: "3.9"

services:

  # Keycloak uses a postgres database
  keycloak_database:
    image: postgres:16.1-bookworm
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: "256M"
    container_name: "keycloak_database"
    ports:
      - "127.0.0.1:${DATABASE_EXTERNAL_TCP_PORT}:${DATABASE_INTERNAL_TCP_PORT}"
    volumes:
      - ./docker/data/keycloak_db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: $DATABASE_USER
      POSTGRES_PASSWORD: $DATABASE_PASSWORD
      POSTGRES_DB: $DATABASE_NAME

  # The keycloack service itself, depends on the availability of the database
  keycloak_keycloak:
    image: keycloak/keycloak:23.0.6
    deploy:
      resources:
        limits:
          cpus: "2"
          memory: "2G"
    container_name: keycloak_keycloak
    depends_on:
      - keycloak_database
    ports:
      - "127.0.0.1:${KEYCLOAK_EXTERNAL_TCP_PORT}:${KEYCLOAK_INTERNAL_TCP_PORT}"
    environment:
      - KEYCLOAK_ADMIN=$KEYCLOAK_ADMIN
      - KEYCLOAK_ADMIN_PASSWORD=$KEYCLOAK_ADMIN_PASSWORD
      - KC_DB=postgres
      - KC_DB_URL=jdbc:postgresql://keycloak_database:${DATABASE_INTERNAL_TCP_PORT}/$DATABASE_NAME
      - KC_DB_USERNAME=$DATABASE_USER
      - KC_DB_PASSWORD=$DATABASE_PASSWORD

    command: start-dev

  keycloak_caddy:
      image: caddy:2.7.6-alpine
      deploy:
        resources:
          limits:
            cpus: "2"
            memory: "2G"
      ports:
        - "127.0.0.1:9000:80"
      container_name: keycloak_caddy
      volumes:
        - $PWD/Caddyfile:/etc/caddy/Caddyfile

  # The python api backend, depends on the keycloak service
  keycloak_backend:
    image: keycloak/backend
    deploy:
      resources:
        limits:
          cpus: "2"
          memory: "2G"
    build:
      context: backend
      target: dev
    depends_on:
      - keycloak_keycloak
    volumes:
      - ./backend:/app
      - ./docker/data/backend_homedir:/root
    environment:
      BACKEND_DB_CONNECTION_STRING: "postgresql+asyncpg://${DATABASE_USER}:${DATABASE_PASSWORD}@${DATABASE_HOST}:${DATABASE_INTERNAL_TCP_PORT}/${DATABASE_NAME}"
    command: $BACKEND_COMMAND
  
  # The Nuxt frontend, dependson the keycloak backend 
  keycloak_frontend:
    image: keycloak/frontend
    deploy:
      resources:
        limits:
          cpus: "2"
          memory: "2G"
    build:
      context: frontend
      target: dev
    depends_on:
      - keycloak_backend
    volumes:
      - ./frontend:/app
      - ./docker/data/frontend_homedir:/root
    command: $FRONTEND_COMMAND
